=== SANJANAPUTHAN/day15/Component/products.dtd
<!ELEMENT product (item+)>
<!ELEMENT item (item_id+,item_name+,quantity*,price?,brand+)>
<!ELEMENT item_id (#PCDATA)>
<!ELEMENT item_name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT brand (#PCDATA)>

=== SANJANAPUTHAN/day15/Component/products.xml
<!DOCTYPE product SYSTEM "products.dtd">
<product>
<item>
	<item_id>101</item_id>
	<item_name>soap</item_name>
	<quantity>30</quantity>
	<price>90</price>
	<brand>pears</brand>
</item>
<item>
	<item_id>102</item_id>
	<item_name>shampoo</item_name>
	<quantity>40</quantity>
	<price>100</price>
	<brand>sunsilk</brand>
</item>
</product>
